[package]
name = "foub"
version = "0.1.0"
authors = ["Dennis <dennis@obsproject.com>"]
edition = "2021"
autobins = false

# Main tool
[[bin]]
name = "foub"
path = "src/main.rs"

# Standalone delta patch creator that will run on Linux as well
[[bin]]
name = "create-deltas"
path = "src/cli_delta.rs"

[dependencies]
# general
walkdir = "2"
serde = { version = "1.0.142", features = ["derive"] }
serde_json = "1.0.83"
# cli/config
clap = { version = "3.2.16", features = ["derive"] }
toml = "0.5.9"
# delta patching
bsdiff = "0.1.6"
xz2 = "0.1.7"
# hashing
blake2 = "0.10.4"
# parallel processing
rayon = "1.5.3"
indicatif = { version = "0.17.0", features = ["rayon"] }
hashbrown = { version = "0.12", features = ["rayon", "serde"] }
