name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build (Debug)
        run: cargo build

      - name: Build (Release)
        run: cargo build -r

      - name: Run Tests
        run: cargo test
