name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v1

      - name: Build (Debug)
        run: cargo build

      - name: Build (Release)
        run: cargo build -r
