name: Test Update Building

on:
  workflow_dispatch:

jobs:
  bouf:
    runs-on: windows-latest
    name: Prepare OBS Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Restore Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install pandoc
        run: choco install pandoc

      - name: Create self-signed cert
        run: New-SelfSignedCertificate -DnsName "OBS Test" -Type CodeSigning -KeyAlgorithm ECDSA_nistP256 -CertStoreLocation "Cert:\CurrentUser\My"

      - name: Download and Extract build
        run: |
          mkdir test\new
          mkdir test\out
          mkdir test\old
          Invoke-WebRequest -Uri "https://github.com/obsproject/obs-studio/releases/download/27.1.3/OBS-Studio-27.1.3-Full-x64.zip" -OutFile "oldest.zip"
          Invoke-WebRequest -Uri "https://github.com/obsproject/obs-studio/releases/download/27.2.4/OBS-Studio-27.2.4-Full-x64.zip" -OutFile "older.zip"
          Invoke-WebRequest -Uri "https://github.com/obsproject/obs-studio/releases/download/28.0.0/OBS-Studio-28.0-Full-x64.zip" -OutFile "old.zip"
          Invoke-WebRequest -Uri "https://github.com/obsproject/obs-studio/releases/download/28.0.1/OBS-Studio-28.0.1-Full-x64.zip" -OutFile "new.zip"
          7z x new.zip -o"test/new"
          7z x old.zip -o"test/old/28.0.0"
          7z x older.zip -o"test/old/27.2.4"
          7z x oldest.zip -o"test/old/27.1.3"

      - name: Build (Release)
        run: cargo build -r

      - name: Run bouf
        run: target/release/bouf --config extra/ci/config.toml --version 28.0.1 -i test/new -p test/old -o test/out --clear-output

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: obs_distribution
          path: test/out
